- name: "[Linux] Сбор системных данных (COMMAND)"
  ansible.builtin.command: uptime
  register: linux_cmd_results
  changed_when: false

- name: "[Linux] Сбор данных о памяти (SHELL)"
  ansible.builtin.shell: |
    set -o pipefail
    free -m | grep Mem
  args:
    executable: /bin/bash
  register: mem_info
  changed_when: false
