- name: "[Linux] Состояние файла конфигурации (COPY)"
  ansible.builtin.copy:
    src: "{{ linux_config_src }}"
    dest: "{{ linux_config_dest }}"
    owner: root
    group: root
    mode: '0644'
  notify: "Перезагрузить службу nginx"
  when: infra_state == 'present'

- name: "[Linux] Удаление файла конфигурации (FILE)"
  ansible.builtin.file:
    path: "{{ linux_config_dest }}"
    state: absent
  when: infra_state == 'absent'
