- name: "[Linux] Копирование файла конфигурации с контроллера"
  ansible.builtin.copy:
    src: "{{ linux_config_src }}"
    dest: "{{ linux_config_dest }}"
    owner: root
    group: root
    mode: '0644'
  notify: "Перезагрузить службу nginx"
