- name: "[Linux] Состояние сетевых утилит и инструментов мониторинга"
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ infra_state }}"
    update_cache: true
  loop: "{{ linux_packages }}"
