#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/linux_common

- name: "[Linux] Состояние сетевых подключений (PING)"
  ansible.builtin.include_tasks: ping.yml

- name: "[Linux] Состояние программных пакетов (APT)"
  ansible.builtin.include_tasks: install.yml

- name: "[Linux] Состояние правил фаервола (UFW)"
  ansible.builtin.include_tasks: ufw_rules.yml

- name: "[Linux] Состояние конфигурационных файлов (COPY)"
  ansible.builtin.include_tasks: copy.yml

- name: "[Linux] Состояние настроек DNS (LINEINFILE)"
  ansible.builtin.include_tasks: add_dns_line.yml

- name: "[Linux] Состояние учетных записей пользователей (USER)"
  ansible.builtin.include_tasks: user.yml

- name: "[Linux] Состояние системных служб (SERVICE)"
  ansible.builtin.include_tasks: service.yml

- name: "[Linux] Состояние диагностических проверок (COMMAND)"
  ansible.builtin.include_tasks: commands.yml

# --- ПРИМЕР ИСПОЛЬЗОВАНИЯ ШАБЛОНОВ (Templates) ---
# Модуль 'template' берет файл из директории 'templates/', 
# подставляет в него переменные и копирует на сервер.
#
# - name: "[Linux] Генерация конфигурации из шаблона"
#   ansible.builtin.template:
#     src: example_config.conf.j2
#     dest: /etc/example_config.conf
#     owner: root
#     group: root
#     mode: '0644'
