- name: "[Linux] Контроль состояния службы nginx"
  ansible.builtin.service:
    name: nginx
    state: "{{ (infra_state == 'absent') | ternary('stopped', 'started') }}"
    enabled: "{{ (infra_state == 'absent') | ternary('no', 'yes') }}"
