- name: "[Linux] Установка фаервола (UFW)"
  ansible.builtin.apt:
    name: ufw
    state: present

- name: "[Linux] Открытие портов HTTP (80) и HTTPS (443) в фаерволе (UFW)"
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    delete: "{{ (infra_state == 'absent') | ternary('yes', 'no') }}"
  loop:
    - 22
    - 80
    - 443

- name: "[Linux] Включение фаервола и установка политики по умолчанию"
  community.general.ufw:
    state: "{{ (infra_state == 'absent') | ternary('disabled', 'enabled') }}"
    policy: "{{ (infra_state == 'absent') | ternary('allow', 'deny') }}"
    direction: incoming
