- name: "[Linux] Состояние учетной записи {{ linux_user_name }}"
  ansible.builtin.user:
    name: "{{ linux_user_name }}"
    comment: "Пользователь для управления веб-сервером"
    shell: "{{ linux_user_shell }}"
    create_home: yes
    password: "{{ vault_user_password | password_hash('sha512') }}"
    state: present
# для корректной передачи пароля необходима библиотека passlib на ansible контроллере / pip install passlib
