---
- name: "[Linux] Состояние учетных записей пользователей (USER)"
  ansible.builtin.user:
    name: "{{ linux_user_name }}"
    shell: "{{ linux_user_shell }}"
    # Пароль обязательно должен быть захеширован (например, sha512)
    # На контроллере обязательно должна быть библиотека passlib / pip install passlib
    password: "{{ vault_user_password | password_hash('sha512') }}"
    state: "{{ infra_state }}"
