---
- name: "[Linux] Состояние учетных записей пользователей (USER)"
  ansible.builtin.user:
    name: "{{ linux_user_name }}"
    shell: "{{ linux_user_shell }}"
    password: "{{ vault_user_password }}"
    state: "{{ infra_state }}"
