galaxy_info:
  author: "Admin"
  description: "Example role"
  company: "Modular Automation"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - example
dependencies: []
