# defaults file for roles/windows_common
---
# Желаемое состояние инфраструктуры (present или absent)
infra_state: "present"

# Состояние пакетов Chocolatey (установлено)
windows_packages:
  - { name: "7zip.install", description: "Средство архивации данных" }
  - { name: "notepadplusplus.install", description: "Редактор текстовых файлов" }

# Параметры учетных записей Windows
windows_user_name: "test-user"
windows_user_description: "Пользователь для управления Win-сервером"

# Пути к файлам конфигурации
windows_config_src: "../files/server.conf"
windows_config_dest: 'C:\server.conf'
