- name: "[Windows] Получение системных данных (PowerShell 7)"
  ansible.windows.win_shell: Get-Uptime
  args:
    executable: pwsh
  register: win_cmd_results
  changed_when: false

- name: "[Windows] Получение имени узла (CMD)"
  ansible.windows.win_shell: hostname
  register: win_hostname
  changed_when: false
