- name: "[Windows] Получение системных данных (PowerShell 7)"
  ansible.windows.win_shell: Get-Uptime | Select-Object -Property Days, Hours, Minutes, Seconds
  args:
    executable: pwsh
  register: win_cmd_results
  changed_when: false

- name: "[Windows] Вывод данных о системном аптайме (PowerShell 7)"
  ansible.builtin.debug:
    msg: "{{ win_cmd_results.stdout_lines }}"

- name: "[Windows] Получение имени узла (CMD)"
  ansible.windows.win_shell: hostname
  register: win_hostname
  changed_when: false

- name: "[Windows] Вывод имени узла (CMD)"
  ansible.builtin.debug:
    msg: "{{ win_hostname.stdout_lines }}"
