#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/windows_common

- name: "[Windows] Состояние доступности узла (WIN_PING)"
  ansible.builtin.include_tasks: ping.yml

- name: "[Windows] Состояние менеджера пакетов Chocolatey (WIN_SHELL)"
  ansible.builtin.include_tasks: install.yml

- name: "[Windows] Состояние правил брандмауэра (WIN_FIREWALL_RULE)"
  ansible.builtin.include_tasks: firewall.yml

- name: "[Windows] Состояние файлов на диске (WIN_COPY)"
  ansible.builtin.include_tasks: copy.yml

- name: "[Windows] Состояние учетных записей (WIN_USER)"
  ansible.builtin.include_tasks: user.yml

- name: "[Windows] Состояние системных служб (WIN_SERVICE)"
  ansible.builtin.include_tasks: service.yml

- name: "[Windows] Состояние диагностических команд (WIN_SHELL)"
  ansible.builtin.include_tasks: commands.yml

# --- ПРИМЕР ИСПОЛЬЗОВАНИЯ ШАБЛОНОВ (Templates) ---
# Модуль 'win_template' берет файл из 'templates/', 
# подставляет в него переменные и копирует на сервер.
#
# - name: "[Windows] Генерация конфигурации из шаблона"
#   ansible.windows.win_template:
#     src: example_config.txt.j2
#     dest: C:\example_config.txt
