---
- name: "[Windows] Состояние учетных записей (WIN_USER)"
  ansible.windows.win_user:
    name: "{{ windows_user_name }}"
    comment: "{{ windows_user_comment }}"
    password: "{{ vault_user_password }}"
    state: "{{ infra_state }}"
