- name: "[Windows] Состояние учетной записи test-user"
  ansible.windows.win_user:
    name: test-uset
    description: "Пользователь для управления Windows"
    password: "{{ vault_user_password }}"
    state: present

