- name: "[Windows] Состояние учетной записи {{ windows_user_name }}"
  ansible.windows.win_user:
    name: "{{ windows_user_name }}"
    description: "Пользователь для управления Windows"
    password: "{{ vault_user_password }}"
    state: "{{ infra_state }}"

