---
# roles/linux_common/defaults/main.yml
# Переменные по умолчанию для linux_common
# Могут быть переопределены в инвентаре или в плейбуке

linux_packages:
  - { name: "nginx", description: "веб-сервер nginx" }
  - { name: "git", description: "система контроля версий git" }
  - { name: "speedtest-cli", description: "Инструмент проверки скорости сети" }
  - { name: "iotop", description: "Инструмент мониторинга i/o" }
  - { name: "nethogs", description: "Инструмент мониторинга подключений" }

linux_user_name: "test-user"
linux_user_shell: "/bin/bash"
