# defaults file for roles/linux_common
---
# Желаемое состояние инфраструктуры (present или absent)
infra_state: "present"

# Список пакетов, состояние которых должно быть "present" (установлено)
linux_packages:
  - { name: "nginx", description: "веб-сервер nginx" }
  - { name: "git", description: "система контроля версий git" }
  - { name: "speedtest-cli", description: "Инструмент проверки скорости сети" }
  - { name: "iotop", description: "Инструмент мониторинга i/o" }
  - { name: "nethogs", description: "Инструмент мониторинга подключений" }

# Параметры учетной записи пользователя
linux_user_name: "test-user"
linux_user_shell: "/bin/bash"

# Пути к файлам конфигурации
linux_config_src: "../files/server.conf"
linux_config_dest: "/etc/server.conf"
