- name: "[Linux] Состояние сетевых утилит и инструментов мониторинга"
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  loop:
    - { name: "nginx", description: "веб-сервер nginx" }
    - { name: "git", description: "система контроля версий git" }
    - { name: "speedtest-cli", description: "Инструмент проверки скорости сети" }
    - { name: "iotop", description: "Инструмент мониторинга i/o" }
    - { name: "nethogs", description: "Инструмент мониторинга подключений" }
