---
- name: "[Выборочно] Настройка Windows-серверов"
  hosts: "{{ target | default('win_servers') }}"

  tasks:
    # Шаг 1: Подгружаем переменные роли
    - name: "Загрузка переменных по умолчанию из роли windows_common"
      ansible.builtin.include_vars:
        file: ../roles/windows_common/defaults/main.yml

    # Шаг 2: Выбираем нужные задачи
    - name: "Блок 1: Проверка доступности (WIN_PING)"
      ansible.builtin.include_tasks: ../roles/windows_common/tasks/ping.yml

    - name: "Блок 2: Установка софта через Chocolatey"
      ansible.builtin.include_tasks: ../roles/windows_common/tasks/install.yml

    - name: "Блок 3: Копирование конфигурационных файлов"
      ansible.builtin.include_tasks: ../roles/windows_common/tasks/copy.yml

    - name: "Информационное сообщение"
      ansible.builtin.debug:
        msg: "Выборочная настройка Windows завершена. Мы не настраивали фаервол и пользователей."
