name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install ansible.windows
          ansible-galaxy collection install community.windows
          ansible-galaxy collection install community.general
          ansible-galaxy collection install chocolatey.chocolatey

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
